project:
  type: book
  output-dir: docs    # プロジェクト全体の出力先を docs/ に変更

book:
  title: "【物理基礎】波とエネルギー"
  author: "phys-ken"
  date: "2025/3/2"
  chapters:
    - index.qmd
    - nami_no_arawashikata.qmd
    - renzokuha.qmd
    - kasaneawase_hansya.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual
